LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# bin
include $(CLEAR_VARS)
LOCAL_MODULE := ccci_fsd
LOCAL_SRC_FILES := bin/ccci_fsd
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ccci_mdinit
LOCAL_SRC_FILES := bin/ccci_mdinit
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gsm0710muxd
LOCAL_SRC_FILES := bin/gsm0710muxd
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gsm0710muxdmd2
LOCAL_SRC_FILES := bin/gsm0710muxdmd2
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtkrild
LOCAL_SRC_FILES := bin/mtkrild
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtkrildmd2
LOCAL_SRC_FILES := bin/mtkrildmd2
LOCAL_MODULE_CLASS := bin
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT)/bin
include $(BUILD_PREBUILT)

# lib
include $(CLEAR_VARS)
LOCAL_MODULE := libaed
LOCAL_MODULE_OWNER := MediaTek
LOCAL_SRC_FILES := lib/libaed.so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librilmtk
LOCAL_MODULE_OWNER := MediaTek
LOCAL_SRC_FILES := lib/librilmtk.so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librilmtkmd2
LOCAL_MODULE_OWNER := MediaTek
LOCAL_SRC_FILES := lib/librilmtkmd2.so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtk-ril
LOCAL_MODULE_OWNER := MediaTek
LOCAL_SRC_FILES := lib/mtk-ril.so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtk-rilmd2
LOCAL_MODULE_OWNER := MediaTek
LOCAL_SRC_FILES := lib/mtk-rilmd2.so
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

