LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE = slpd
LOCAL_MODULE_CLASS = EXECUTABLES
LOCAL_MODULE_OWNER = mtk
LOCAL_PROPRIETARY_MODULE = true
LOCAL_MODULE_TAGS = optional
LOCAL_SHARED_LIBRARIES = libcrypto libssl libc++
LOCAL_MULTILIB = 32
LOCAL_SRC_FILES_32 = arm/slpd
include $(BUILD_PREBUILT)
