#!/system/bin/sh

# Получаем значения перед запуском цикла:
echo WakeLockForNoReboots > /sys/power/wake_lock # Блокируем сон при запуске скрипта
mod_scal_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` # Получаем текущие права на файл
mod_scal_max_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` # Получаем текущие права на файл
mod_info_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq` # Получаем текущие права на файл
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Устанавливаем права на чтение/запись
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Устанавливаем права на чтение/запись
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Устанавливаем права на чтение/запись
current_min_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` # Получаем текущую минимальную частоту
current_max_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` # Получаем текущую максимальную частоту
info_min_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq` # Получаем минимально возможную частоту
chmod "$mod_scal_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Восстанавливаем права
chmod "$mod_scal_max_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Восстанавливаем права
chmod "$mod_info_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Восстанавливаем права

# Цикл
(while true; do # Выполняем тело цикла
if [ wake=`cat /sys/power/wait_for_fb_sleep` ]; then # Если экран отключен, тогда
    echo WakeLockForNoReboots > /sys/power/wake_lock # Блокируем сон (deep sleep)
    mod_scal_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` # Получаем текущие права на файл минимальной частоты
    mod_scal_max_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` # Получаем текущие права на файл максимальной частоты
    mod_info_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq` # Получаем текущие права на файл
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Устанавливаем права на чтение/запись
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Устанавливаем права на чтение/запись
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Устанавливаем права на чтение/запись
    current_min_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` # Получаем текущую минимальную частоту
    current_max_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` # Получаем текущую максимальную частоту
    info_min_freq=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq` # Получаем минимально возможную частоту
    echo "$info_min_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Устанавливаем минимально возможную минимальную частоту
    echo "$info_min_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Устанавливаем минимально возможную максимальную частоту
    chmod "$mod_scal_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Восстанавливаем права
    chmod "$mod_scal_max_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Восстанавливаем права
    chmod "$mod_info_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Восстанавливаем права
fi
if [ wake=`cat /sys/power/wait_for_fb_wake` ]; then # Если экран включен, тогда
    echo WakeLockForNoReboots > /sys/power/wake_unlock # Отключаем блокировку сна
    mod_scal_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq` # Получаем текущие права на файл минимальной частоты
    mod_scal_max_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq` # Получаем текущие права на файл максимальной частоты
    mod_info_min_freq_file=`stat -c %a /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq` # Получаем текущие права на файл
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Устанавливаем права на чтение/запись
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Устанавливаем права на чтение/запись
    chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Устанавливаем права на чтение/запись
    echo "$current_min_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Восстанавливаем минимальную частоту
    echo "$current_max_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Восстанавливаем максимальную частоту
    chmod "$mod_scal_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq # Восстанавливаем права на файл минимальной частоты
    chmod "$mod_scal_max_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq # Восстанавливаем права на файл максимальной частоты
    chmod "$mod_info_min_freq_file" /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq # Восстанавливаем права
fi
done &)

